### ISSUE TITLE
[FEAT] decision 수정

### ISSUE THREAD

**Issue by jinwooseok** [goalajuma/BackEnd#114]
### ✨ Describe

decision을 수정합니다.

### ✅ Tasks

- [x] 해당 투표에 대해 이미 한 옵션 번호 확인
- [x] 해당 옵션 count  -- 처리
- [x] 새로운 옵션 count ++ 처리

### 🕰️ Estimated Time of Completion

1h
