### ISSUE TITLE
[FEAT] 대댓글, 공감 기능 entity, web 부분 완성

### ISSUE THREAD

**Issue by jinwooseok** [goalajuma/BackEnd#140]
### ✨ Describe

대댓글, 공감 기능을 위해 entity, web 파트 수정

### ✅ Tasks

- [x] 댓글 entity 수정
- [x] 새로운 api controller 완성
- [x] 기존 api dto 수정

### 🕰️ Estimated Time of Completion

48
