### ISSUE TITLE
[REFACTOR] 댓글 생성 및 조회 서비스 로직 수정

### ISSUE THREAD

**Issue by jinwooseok** [goalajuma/BackEnd#148]
### 🔨 Describe

익명 기능, 공감 기능 추가에 따른 서비스 로직 변경.

### ✅ Tasks

- [x] 익명 기능 추가로 인한 유저명 변경 로직 추가
- [x] 대댓글 추가로 인해 삭제 시 변경사항 추가
- [x] 공감 기능 추가

### 🕰️ Estimated Time of Completion

1
