### ISSUE TITLE
[FEAT] 새로 만든 댓글 API(공감, 대댓글 관련) 테스트 추가

### ISSUE THREAD

**Issue by jinwooseok** [goalajuma/BackEnd#151]
### ✨ Describe

새로 생긴 API TEST, SERVICE TEST 추가

### ✅ Tasks

- [ ] reply create api test
- [ ] reply create service test
- [ ] likey update api test
- [ ] likey update service test
- [ ] likey repository test

### 🕰️ Estimated Time of Completion

?
