### ISSUE TITLE
[REFACTOR] 댓글 테스트 추가

### ISSUE THREAD

**Issue by jinwooseok** [goalajuma/BackEnd#172]
### 🔨 Describe

1. 댓글 조회 시 익명, 공감, 대댓글이 잘 오는지 테스트 추가
2. 익명 조회 시 글쓴이인 경우에 대한 테스트 추가
3. 댓글 공감 누를 시 잘 작동하는지 테스트 추가
4. 댓글 조회 시 삭제된 댓글이 잘 적용되는지 테스트 추가
5. 대댓글 생성 기능 테스트 추가
6. 댓글 업데이트 기능이 잘 작동하는지 테스트 추가

### ✅ Tasks

- [ ] 댓글 조회 시 익명, 공감, 대댓글이 잘 오는지 테스트 추가
- [ ]익명 조회 시 글쓴이인 경우에 대한 테스트 추가
- [ ] 댓글 공감 누를 시 잘 작동하는지 테스트 추가
- [ ] 댓글 업데이트 기능이 잘 작동하는지 테스트 추가
- [ ] 대댓글 생성 기능 테스트 추가
- [ ]  댓글 조회 시 삭제된 댓글이 잘 적용되는지 테스트 추가

### 🕰️ Estimated Time of Completion

long time

### 🙋🏻 More

ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
