### ISSUE TITLE
[Test] 투표 도메인 테스트 코드 추가 

### ISSUE THREAD

**Issue by PHS00** [goalajuma/BackEnd#173]
### ✨ Describe

새로운 기능에 대한 테스트 코드를 추가합니다.

### ✅ Tasks

- [ ] 투표 옵션 추가
- [ ] 마감 시간 연장
- [ ] 투표 재오픈
- [ ] 검색 기록 조회 
- [ ] 투표 삭제
